---
- name: Install packages
  ansible.builtin.package:
    name: bash
    state: present

- name: Install munin-node
  ansible.builtin.package:
    name: munin-node
    state: present
  notify:
    - Run munin-node-configure-freebsd

- name: Copy munin-node configuration.
  ansible.builtin.template:
    src: munin-node.conf.j2
    dest: /usr/local/etc/munin/munin-node.conf
    owner: root
    group: wheel
    mode: 0644
  notify: Restart munin-node

  # plugin-conf.d parsed in alphabetical order
- name: Generate plugin configuration.
  ansible.builtin.template:
    src: plugin-conf.j2
    dest: /usr/local/etc/munin/plugin-conf.d/nansible.conf
    owner: root
    group: wheel
    mode: 0644
  notify: Restart munin-node

- name: Enable additional plugins.
  ansible.builtin.file:
    path: "{{ munin_plugin_dest_path }}{{ item.name }}"
    src: "{{ munin_plugin_src_path }}{{ item.plugin | default(item.name) }}"
    state: link
  with_items: "{{ munin_node_plugins }}"
  notify: Restart munin-node

- name: Enable munin in /etc/rc.conf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    regexp: '^munin_node_enable='
    line: munin_node_enable="YES"

- name: Ensure munin-node is running.
  ansible.builtin.command: |
    /usr/local/etc/rc.d/munin-node start
  changed_when: false
  failed_when: false
