---
# Variables ##########
#
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  failed_when: false
  when:
    - ansible_os_family != 'Darwin'

- name: Determine macos version
  set_fact:
    macos_version: "{{ ansible_distribution }}-{{  ansible_distribution_version.split('.')[0] }}.{{  ansible_distribution_version.split('.')[1] }}"
  when:
    - ansible_os_family == 'Darwin'

- name: Include Distribution version specific variables for Mac
  include_vars: "{{ macos_version }}.yml"
  failed_when: false
  when:
    - ansible_os_family == 'Darwin'

- name: set facts based on defaults
  set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is not defined
  with_items:
    "{{ vars | list }}"

##########

- name: include client
  import_tasks: client.yml
  when: run_munin_client is defined


- name: include server
  import_tasks: server.yml
  when: run_munin_server is defined
