---
- name: Restart munin-node
  ansible.builtin.service:
    name: munin-node
    state: restarted

- name: Restart apache
  ansible.builtin.service:
    name: "{{ munin_apache_service }}"
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

# During testing, munin-node-configure had to be run twice. Investigate.
- name: Run munin-node-configure
  args:
    executable: /bin/bash
  changed_when: true
  ansible.builtin.shell: |
    set -o pipefail
    sleep 1
    sudo -u munin /opt/local/sbin/munin-node-configure --suggest --shell | sudo sh
    sleep 1
    sudo -u munin /opt/local/sbin/munin-node-configure --suggest --shell | sudo sh
    sleep 1
    /opt/local/bin/port reload munin
    sleep 1

- name: Run munin-node-configure-freebsd
  args:
    executable: /bin/bash
  changed_when: true
  ansible.builtin.shell: |
    set -xe
    set -o pipefail
    sleep 1
    /usr/local/sbin/munin-node-configure --shell | sh -x
    sleep 1
    # this whole task is hanging
    # /usr/local/sbin/munin-node-configure --shell | sh -x
    # sleep 1
    /usr/local/etc/rc.d/munin-node stop || true
    sleep 1
    /usr/local/etc/rc.d/munin-node start || true
  failed_when: false

- name: Restart munin-node-mac
  ansible.builtin.command: |
    /opt/local/bin/port reload munin
  changed_when: false
