---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Run whoami without become.
      ansible.builtin.command: whoami
      changed_when: false
      become: false
      register: whoami
    - name: Print whoami
      ansible.builtin.debug:
        var: whoami
        verbosity: 4
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
    - name: Fix coreutils-single on containers
      ansible.builtin.command: dnf install -y --allowerasing coreutils
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version| int > 7
      changed_when: false
    - name: Install iproute2
      ansible.builtin.package:
        name: iproute2
        state: present
      when:
        - ansible_os_family == 'Debian'
      changed_when: false
    - name: Install iproute
      ansible.builtin.package:
        name: iproute
        state: present
      when:
        - ansible_os_family == 'RedHat'
      changed_when: false
    # debugging.
    - name: Create cron.d
      ansible.builtin.file:
        path: /etc/cron.d
        state: directory
        mode: '0755'
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version| int > 7
    - name: Re-run setup
      ansible.builtin.setup:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars
  roles:
    - {role: 'sdarwin.munin', run_munin_client: true}
    - {role: 'sdarwin.munin', run_munin_server: true}

  post_tasks:
    - name: Add munin.example.com to hosts file
      ansible.builtin.shell: echo "127.0.1.1  munin.example.com" >> /etc/hosts  # noqa command-instead-of-shell
      changed_when: false

    - name: Run munin cron
      ansible.builtin.shell: su - munin --shell=/bin/bash /usr/bin/munin-cron  # noqa command-instead-of-shell
      retries: 5
      delay: 30
      register: result
      until: result.rc == 0
      changed_when: false

    - name: Pause after cron
      ansible.builtin.pause:
        seconds: 30
      changed_when: false

    - name: Check website
      ansible.builtin.uri:
        url: https://munin.example.com
        url_username: muninadmin
        url_password: Password1change
        validate_certs: false
        return_content: true
      register: this
      failed_when: "'Overview' not in this.content"
