---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .

# platforms:
#   - name: instance
#     image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
#     command: ${MOLECULE_DOCKER_COMMAND:-""}
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#       - /var/lib/docker
#     privileged: true
#     pre_build_image: true
#     groups:
#       - monitoring-servers

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - monitoring-servers

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
