---
- name: Collect Facts
  hosts: all:!windows:!blackbox
  remote_user: ubuntu
  become: true
  tasks:
    - name: Collect facts
      ansible.builtin.setup:

- name: Collect Facts (windows)
  hosts: windows
  tasks:
    - name: Collect facts
      ansible.builtin.setup:

- name: Monitoring Servers
  hosts: monitoring-servers
  remote_user: ubuntu
  become: true
  roles:
    # this is the Ansible Galaxy name, you could change it to ansible-munin if directly downloading from github
    - {role: 'sdarwin.munin', run_munin_server: true}
